<?php

namespace Cyberfusion\CoreApi\Enums;

enum ObjectModelNameEnum: string
{
    case BorgArchive = 'BorgArchive';
    case BorgRepository = 'BorgRepository';
    case ServiceAccountToCluster = 'ServiceAccountToCluster';
    case Region = 'Region';
    case ServiceAccountToCustomer = 'ServiceAccountToCustomer';
    case Cluster = 'Cluster';
    case Customer = 'Customer';
    case Cms = 'Cms';
    case FpmPool = 'FpmPool';
    case VirtualHost = 'VirtualHost';
    case PassengerApp = 'PassengerApp';
    case Database = 'Database';
    case CertificateManager = 'CertificateManager';
    case BasicAuthenticationRealm = 'BasicAuthenticationRealm';
    case Cron = 'Cron';
    case Daemon = 'Daemon';
    case MariadbEncryptionKey = 'MariadbEncryptionKey';
    case FirewallRule = 'FirewallRule';
    case HostsEntry = 'HostsEntry';
    case NodeAddOn = 'NodeAddOn';
    case IpAddress = 'IpAddress';
    case SecurityTxtPolicy = 'SecurityTxtPolicy';
    case DatabaseUser = 'DatabaseUser';
    case DatabaseUserGrant = 'DatabaseUserGrant';
    case HtpasswdFile = 'HtpasswdFile';
    case HtpasswdUser = 'HtpasswdUser';
    case MailAccount = 'MailAccount';
    case MailAlias = 'MailAlias';
    case MailDomain = 'MailDomain';
    case Node = 'Node';
    case RedisInstance = 'RedisInstance';
    case DomainRouter = 'DomainRouter';
    case MailHostname = 'MailHostname';
    case Certificate = 'Certificate';
    case RootSshKey = 'RootSshKey';
    case SshKey = 'SshKey';
    case BorgRepositorySshKey = 'BorgRepositorySshKey';
    case UnixUser = 'UnixUser';
    case UnixUserRabbitmqCredentials = 'UnixUserRabbitmqCredentials';
    case HaproxyListen = 'HaproxyListen';
    case HaproxyListenToNode = 'HaproxyListenToNode';
    case UrlRedirect = 'UrlRedirect';
    case RegionToCustomer = 'RegionToCustomer';
    case ServiceAccount = 'ServiceAccount';
    case ServiceAccountServer = 'ServiceAccountServer';
    case CustomConfig = 'CustomConfig';
    case ClustersPhpProperties = 'ClustersPhpProperties';
    case ClustersNodejsProperties = 'ClustersNodejsProperties';
    case ClustersBorgProperties = 'ClustersBorgProperties';
    case ClustersKernelcareProperties = 'ClustersKernelcareProperties';
    case ClustersNewRelicProperties = 'ClustersNewRelicProperties';
    case ClustersRedisProperties = 'ClustersRedisProperties';
    case ClustersPostgresqlProperties = 'ClustersPostgresqlProperties';
    case ClustersMariadbProperties = 'ClustersMariadbProperties';
    case ClustersMeilisearchProperties = 'ClustersMeilisearchProperties';
    case ClustersGrafanaProperties = 'ClustersGrafanaProperties';
    case ClustersSinglestoreProperties = 'ClustersSinglestoreProperties';
    case ClustersElasticsearchProperties = 'ClustersElasticsearchProperties';
    case ClustersRabbitmqProperties = 'ClustersRabbitmqProperties';
    case ClustersMetabaseProperties = 'ClustersMetabaseProperties';
    case ClustersUnixUsersProperties = 'ClustersUnixUsersProperties';
    case ClustersLoadBalancingProperties = 'ClustersLoadBalancingProperties';
    case ClustersFirewallProperties = 'ClustersFirewallProperties';
    case ClustersOsProperties = 'ClustersOsProperties';
}
