<?php

namespace Cyberfusion\CoreApi\Enums;

enum ObjectModelNameEnum: string
{
    case BorgArchive = 'BorgArchive';
    case BorgRepository = 'BorgRepository';
    case ServiceAccountToCluster = 'ServiceAccountToCluster';
    case Region = 'Region';
    case ServiceAccountToCustomer = 'ServiceAccountToCustomer';
    case Cluster = 'Cluster';
    case Customer = 'Customer';
    case CMS = 'CMS';
    case FPMPool = 'FPMPool';
    case VirtualHost = 'VirtualHost';
    case PassengerApp = 'PassengerApp';
    case Database = 'Database';
    case CertificateManager = 'CertificateManager';
    case BasicAuthenticationRealm = 'BasicAuthenticationRealm';
    case Cron = 'Cron';
    case Daemon = 'Daemon';
    case MariaDBEncryptionKey = 'MariaDBEncryptionKey';
    case FirewallRule = 'FirewallRule';
    case HostsEntry = 'HostsEntry';
    case NodeAddOn = 'NodeAddOn';
    case IPAddress = 'IPAddress';
    case SecurityTXTPolicy = 'SecurityTXTPolicy';
    case DatabaseUser = 'DatabaseUser';
    case DatabaseUserGrant = 'DatabaseUserGrant';
    case HtpasswdFile = 'HtpasswdFile';
    case HtpasswdUser = 'HtpasswdUser';
    case MailAccount = 'MailAccount';
    case MailAlias = 'MailAlias';
    case MailDomain = 'MailDomain';
    case Node = 'Node';
    case RedisInstance = 'RedisInstance';
    case DomainRouter = 'DomainRouter';
    case MailHostname = 'MailHostname';
    case Certificate = 'Certificate';
    case RootSSHKey = 'RootSSHKey';
    case SSHKey = 'SSHKey';
    case BorgRepositorySshKey = 'BorgRepositorySshKey';
    case UNIXUser = 'UNIXUser';
    case UNIXUserRabbitMQCredentials = 'UNIXUserRabbitMQCredentials';
    case HAProxyListen = 'HAProxyListen';
    case HAProxyListenToNode = 'HAProxyListenToNode';
    case URLRedirect = 'URLRedirect';
    case RegionToCustomer = 'RegionToCustomer';
    case ServiceAccount = 'ServiceAccount';
    case ServiceAccountServer = 'ServiceAccountServer';
    case CustomConfig = 'CustomConfig';
    case ClustersPhpProperties = 'clusters_php_properties';
    case ClustersNodejsProperties = 'clusters_nodejs_properties';
    case ClustersBorgProperties = 'clusters_borg_properties';
    case ClustersKernelcareProperties = 'clusters_kernelcare_properties';
    case ClustersNewRelicProperties = 'clusters_new_relic_properties';
    case ClustersRedisProperties = 'clusters_redis_properties';
    case ClustersPostgresqlProperties = 'clusters_postgresql_properties';
    case ClustersMariadbProperties = 'clusters_mariadb_properties';
    case ClustersMeilisearchProperties = 'clusters_meilisearch_properties';
    case ClustersGrafanaProperties = 'clusters_grafana_properties';
    case ClustersSinglestoreProperties = 'clusters_singlestore_properties';
    case ClustersElasticsearchProperties = 'clusters_elasticsearch_properties';
    case ClustersRabbitmqProperties = 'clusters_rabbitmq_properties';
    case ClustersMetabaseProperties = 'clusters_metabase_properties';
    case ClustersUnixUsersProperties = 'clusters_unix_users_properties';
    case ClustersLoadBalancingProperties = 'clusters_load_balancing_properties';
    case ClustersFirewallProperties = 'clusters_firewall_properties';
    case ClustersOsProperties = 'clusters_os_properties';
}
